name: randoclub
description: The app for all hiking lovers 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # This package provides internationalization and localization facilities,
  # including message translation, plurals and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.16.1

  # A collection of loading indicators animated with flutter.
  flutter_spinkit: ^4.1.1+1

  # Flutter plugins for other Firebase products (Google Sign in)
  firebase_auth: ^0.15.4
  google_sign_in: ^4.1.1

  # for using Toast messages
  fluttertoast: ^3.1.3

  provider: ^4.0.4

  # Chopper is an http client generator using source_gen and inspired by Retrofit.
  chopper: ^3.0.1+1

  # A light weight package to show progress dialog. As it is a stateful widget,
  # you can change the text shown on the dialog dynamically.
  progress_dialog: ^1.2.1

  # A Flutter package that helps implement the BLoC pattern.
  flutter_bloc: ^3.2.0

  # Moor is a reactive persistence library for Flutter and Dart, built ontop of sqlite
  moor: ^2.4.0
  moor_ffi: ^0.4.0

  #  Used to find a suitable location to store the database (for moor).
  path_provider:
  path:

  # allows Flutter apps to discover network connectivity
  connectivity: ^0.4.8+1

  # plugin for launching a URL in the mobile platform. Supports iOS and Android.
  url_launcher: ^5.4.2

  # plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera
  image_picker: ^0.6.4

  #  plugin for Android and iOS supports cropping images
  image_cropper: ^1.2.1

  #  plugin for Android and iOS supports compressing images
  flutter_image_compress: ^0.6.5+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: ^3.0.3

  build_runner:
  moor_generator: ^2.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/hiking.jpg
    - assets/loading.gif

  fonts:
      - family: PTSerif
        fonts:
          - asset: assets/fonts/PTSerif-Regular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
